/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 119
#define YY_END_OF_BUFFER 120
static yyconst short int yy_acclist[337] =
    {   0,
      120,  119,  118,  119,  117,  119,  119,   33,  119,    3,
      119,   74,  119,   78,  119,   36,  119,   88,  119,   89,
      119,   70,  119,   68,  119,   94,  119,   69,  119,   96,
      119,   72,  119,  114,  119,   95,  119,   97,  119,   83,
      119,   98,  119,   82,  119,   75,  119,  115,  119,  115,
      119,  115,  119,  115,  119,   90,  119,  119,   91,  119,
       80,  119,  115,  119,  115,  119,  115,  119,  115,  119,
      115,  119,  115,  119,  115,  119,  115,  119,  115,  119,
      115,  119,  115,  119,  115,  119,  115,  119,  115,  119,
      115,  119,   92,  119,   79,  119,   93,  119,   81,  119,

        2,  117,  119,  115,  119,    4,  119,    5,  119,   21,
      119,   34,  119,   35,  119,   11,  119,  119,   12,  119,
      119,   12,  119,   11,  119,  119,   37,  119,  119,   32,
      119,   30,   32,  119,   28,  119,   29,   32,  119,   27,
       32,  119,    1,  119,   87,  105,  107,   71,  102,  100,
      101,   99,  113,   73,  103,  113,  114,   76,   84,   86,
       85,   77,  106,  115,  115,  115,  115,  116,  109,  115,
       44,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      115,   39,  115,  115,   42,  115,   43,  115,  115,  115,
       47,  115,  115,  115,  115,  115,  115,  115,  115,  108,

        2,  115,    4,   21,    8,   10,    9,   14,   15,   16,
       17,   18,   19,    7,   10,   25,   24,   30,   31,   28,
       31,   27,   29,   31,    6,   23,  112,  113,  104,  113,
      113,  111,  110,  115,  115,  115,   57,  115,  115,  115,
      115,  115,   62,  115,  115,  115,  115,  115,   53,  115,
      115,  115,  115,   46,  115,  115,  115,  115,   51,  115,
      115,  115,  115,   22,   26,   30,   31,   31,   29,   31,
      113,  115,   55,  115,   56,  115,  115,  115,  115,  115,
       63,  115,   64,  115,  115,  115,   41,  115,  115,  115,
       48,  115,  115,  115,  115,   54,  115,  115,   20,   38,

      115,  115,   59,  115,   60,  115,  115,  115,  115,  115,
      115,   49,  115,  115,   52,  115,   67,  115,   58,  115,
      115,   65,  115,  115,   40,  115,   45,  115,   50,  115,
      115,   66,  115,   61,  115,   13
    } ;

static yyconst short int yy_accept[267] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,    3,    5,
        7,    8,   10,   12,   14,   16,   18,   20,   22,   24,
       26,   28,   30,   32,   34,   36,   38,   40,   42,   44,
       46,   48,   50,   52,   54,   56,   58,   59,   61,   63,
       65,   67,   69,   71,   73,   75,   77,   79,   81,   83,
       85,   87,   89,   91,   93,   95,   97,   99,  101,  104,
      106,  108,  110,  112,  114,  116,  118,  119,  121,  122,
      124,  126,  127,  129,  130,  132,  135,  137,  140,  143,
      145,  146,  146,  147,  148,  148,  149,  150,  151,  152,

      153,  154,  155,  156,  157,  158,  158,  159,  160,  161,
      162,  163,  164,  165,  166,  167,  168,  169,  169,  170,
      171,  173,  174,  175,  176,  177,  178,  179,  180,  181,
      182,  184,  185,  187,  189,  190,  191,  193,  194,  195,
      196,  197,  198,  199,  200,  201,  202,  203,  204,  205,
      206,  207,  208,  209,  210,  211,  211,  212,  213,  214,
      214,  214,  215,  215,  217,  218,  220,  221,  222,  223,
      225,  226,  227,  228,  229,  229,  230,  231,  231,  232,
      233,  234,  235,  236,  237,  239,  240,  241,  242,  243,
      245,  246,  247,  248,  249,  251,  252,  253,  254,  256,

      257,  258,  259,  261,  262,  263,  264,  264,  264,  265,
      266,  268,  269,  271,  271,  272,  273,  275,  277,  278,
      279,  280,  281,  283,  285,  286,  287,  289,  290,  291,
      293,  294,  295,  296,  298,  299,  299,  300,  302,  303,
      305,  307,  308,  309,  310,  311,  312,  314,  315,  317,
      319,  319,  321,  322,  324,  325,  327,  329,  331,  331,
      332,  334,  334,  336,  337,  337
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    2,    3,    4,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,    1,   26,   27,   27,   27,   27,   28,   29,
       30,   30,   30,   30,   30,   30,   30,   31,   30,   30,
       30,   30,   30,   32,   30,   30,   30,   30,   30,   30,
       33,   34,   35,   36,   30,    1,   37,   38,   39,   40,

       41,   42,   30,   43,   44,   30,   45,   46,   47,   48,
       49,   50,   30,   51,   52,   53,   54,   55,   56,   57,
       58,   30,   59,   60,   61,   62,    1,    1,    2,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[63] =
    {   0,
        1,    2,    2,    3,    1,    1,    2,    1,    1,    1,
        2,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    4,    4,    4,    5,
        5,    5,    1,    3,    1,    1,    4,    4,    4,    4,
        4,    4,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    1,    1,
        1,    1
    } ;

static yyconst short int yy_base[275] =
    {   0,
        0,   59,   60,   61,   64,   70,   76,   82,   98,  110,
      116,  122,  372,  131,  371,  370,  373,  377,  377,  377,
      348,  364,  377,  346,  345,  357,  377,  377,   68,  343,
      377,   45,  346,   72,  110,  377,  377,   83,  341,  116,
      340,    0,  326,  313,  310,  377,   93,  377,  336,   51,
      308,   97,  317,   85,  103,  111,  320,  307,  304,  317,
      120,  302,  105,  308,  377,  327,  377,  377,  377,  118,
        0,  377,    0,  377,  377,  377,  164,  343,  301,  377,
      337,  126,  377,  153,  377,  164,  377,  173,  377,  377,
      377,  340,  377,  377,  335,  321,  377,  377,  377,  377,

      145,  320,  377,  159,  162,  168,  319,  377,  377,  377,
      318,  377,    0,  295,  292,  285,  377,  158,  377,  298,
      285,  295,  298,  286,  291,  140,  293,  283,  279,  280,
        0,  278,    0,    0,  280,  273,    0,  273,  280,  270,
      264,  277,  267,  278,  377,  377,  162,    0,    0,  377,
      377,  377,  377,  377,  377,  277,  377,  377,  377,    0,
      310,  275,  304,  377,  273,  191,  377,  219,  377,  225,
      377,  377,  377,  177,  196,  377,  206,  293,  292,  377,
      377,  259,  269,  268,    0,  267,  270,  254,  252,    0,
      262,  262,  261,  264,    0,  253,  250,  260,    0,  245,

      244,  241,    0,  248,  250,  246,  235,    0,  377,  377,
      232,  238,  245,  270,  269,  247,    0,    0,  236,  241,
      231,  238,    0,    0,  228,  206,    0,  200,  205,    0,
      203,  188,  197,    0,  192,  185,  377,    0,  172,    0,
        0,  172,  156,  162,  154,  167,    0,  145,    0,    0,
      147,    0,  135,    0,   97,    0,    0,    0,   67,   67,
        0,   49,    0,  377,  377,  253,  258,  263,  268,  270,
      275,  280,   84,   72
    } ;

static yyconst short int yy_def[275] =
    {   0,
      265,    1,  266,  266,  267,  267,  267,  267,  267,  267,
      267,  267,  268,  268,  269,  269,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  270,  270,  270,  270,  265,  265,  265,  265,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  265,  265,  265,  265,  265,  270,
      271,  265,  272,  265,  265,  265,  265,  265,   77,  265,
      265,   77,  265,   77,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,

      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  270,  270,  270,  270,  265,  265,  265,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  265,  265,  270,  271,  272,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  273,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,

      270,  270,  270,  270,  270,  270,  265,  274,  265,  265,
      265,  265,  265,  265,  265,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  265,  265,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      265,  270,  270,  270,  270,  270,  270,  270,  265,  270,
      270,  265,  270,  265,    0,  265,  265,  265,  265,  265,
      265,  265,  265,  265
    } ;

static yyconst short int yy_nxt[440] =
    {   0,
       18,   18,   19,   20,   19,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   42,   43,   42,
       44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   42,   56,   42,   57,   42,   58,   59,   60,
       61,   42,   62,   42,   42,   63,   42,   64,   65,   66,
       67,   68,   69,   72,   72,   18,   18,   74,   99,  100,
       75,   18,   18,   74,   76,  237,   75,   18,   18,   18,
       76,   96,   78,   18,   18,   18,   76,  208,   78,  264,
      102,   97,   76,   72,   72,  103,  117,   77,  120,   18,

       18,   18,  121,   77,   80,  107,  108,  263,   81,   79,
       70,   18,   18,   18,  262,   79,   80,   18,   18,   74,
       81,  146,   80,   18,   18,   74,   83,  104,   80,  105,
      126,   82,   83,   86,   87,   88,  164,  106,   89,  110,
      111,  127,  123,   82,  118,  124,  128,  142,  143,   84,
      106,  129,  131,  130,  261,   84,  139,  132,  133,  265,
      140,  117,  134,  164,  174,  146,  166,  167,  168,  147,
      150,  169,  175,  165,  151,  168,  167,  170,  177,  104,
      169,  105,  178,  191,  178,  175,  175,  179,  260,  106,
      259,  192,  258,  211,  167,  212,  174,  152,  169,  175,

      153,  154,  106,  257,  175,  155,  256,  255,  254,  118,
      214,  156,  214,  147,  157,  215,  158,  175,  159,  253,
      160,  212,  167,  212,  252,  174,  169,  212,  167,  213,
      251,  250,  169,  175,  211,  167,  212,  249,  248,  169,
      212,  167,  212,  247,  246,  169,  175,  212,  167,  213,
      245,  244,  169,   71,   71,   71,   71,   71,   73,   73,
       73,   73,   73,   85,   85,   85,   85,   85,   90,   90,
       90,   90,   90,  113,  113,  148,  148,  243,  148,  148,
      149,  242,  241,  149,  149,  240,  239,  238,  215,  215,
      236,  235,  234,  233,  232,  231,  230,  229,  228,  227,

      226,  225,  224,  223,  222,  221,  220,  219,  218,  217,
      216,  179,  179,  207,  210,  207,  209,  207,  206,  205,
      204,  203,  202,  201,  200,  199,  198,  197,  196,  195,
      194,  193,  190,  189,  188,  187,  186,  185,  184,  183,
      182,  181,  180,  176,  173,  172,  171,  163,  162,  161,
      145,  144,  141,  138,  137,  136,  135,  125,  122,  119,
      116,  115,  114,  112,  109,  101,   98,   95,   94,   93,
       92,   91,  265,   18,   18,   18,   17,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,

      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265
    } ;

static yyconst short int yy_chk[440] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,    3,    4,    5,    5,    5,   32,   32,
        5,    6,    6,    6,    5,  274,    6,    7,    7,    7,
        6,   29,    7,    8,    8,    8,    7,  273,    8,  262,
       34,   29,    8,    3,    4,   34,   47,    5,   50,    9,

        9,    9,   50,    6,    9,   38,   38,  260,    9,    7,
        2,   10,   10,   10,  259,    8,   10,   11,   11,   11,
       10,   70,   11,   12,   12,   12,   11,   35,   12,   35,
       54,    9,   12,   14,   14,   14,   82,   35,   14,   40,
       40,   54,   52,   10,   47,   52,   55,   63,   63,   11,
       35,   55,   56,   55,  255,   12,   61,   56,   56,   84,
       61,  118,   56,   84,  101,  147,   86,   86,   86,   70,
       77,   86,  101,   82,   77,   88,   88,   88,  104,  105,
       88,  105,  106,  126,  106,  101,  104,  106,  253,  105,
      251,  126,  248,  166,  166,  166,  174,   77,  166,  104,

       77,   77,  105,  246,  174,   77,  245,  244,  243,  118,
      175,   77,  175,  147,   77,  175,   77,  174,   77,  242,
       77,  168,  168,  168,  239,  177,  168,  170,  170,  170,
      236,  235,  170,  177,  211,  211,  211,  233,  232,  211,
      212,  212,  212,  231,  229,  212,  177,  213,  213,  213,
      228,  226,  213,  266,  266,  266,  266,  266,  267,  267,
      267,  267,  267,  268,  268,  268,  268,  268,  269,  269,
      269,  269,  269,  270,  270,  271,  271,  225,  271,  271,
      272,  222,  221,  272,  272,  220,  219,  216,  215,  214,
      207,  206,  205,  204,  202,  201,  200,  198,  197,  196,

      194,  193,  192,  191,  189,  188,  187,  186,  184,  183,
      182,  179,  178,  165,  163,  162,  161,  156,  144,  143,
      142,  141,  140,  139,  138,  136,  135,  132,  130,  129,
      128,  127,  125,  124,  123,  122,  121,  120,  116,  115,
      114,  111,  107,  102,   96,   95,   92,   81,   79,   78,
       66,   64,   62,   60,   59,   58,   57,   53,   51,   49,
       45,   44,   43,   41,   39,   33,   30,   26,   25,   24,
       22,   21,   17,   16,   15,   13,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,

      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "lex"
#define INITIAL 0
#line 2 "lex"
#include "python.bison_tab.h"
#include "tree_struct.h"
#include <stdio.h>
#include <stdlib.h>
#include <process.h>
#include "printTree.h"
extern int yyparse(void);
void calcIndentation(int* indentStack, int* indexTop, int len, struct DedentStruct* dedents);
struct DedentStruct
{
	int DedentType;
	int count;
};
struct DedentStruct dedents;
int firstEOF = 1;
int secondEOF = 1;
int indexTop = 0;
int indentStack[1000];
int parenthesesOpenCount = 0;
	int squarebracketsOpenCount = 0;
	int curlybracesOpenCount = 0;
	int isLogicalString = 0;
#define YY_NEVER_INTERACTIVE 1
#define ONECOMMENT 1

#define STRING_0 2

#define DOUBLELONGSTRING 3

#define LONGSTRING 4

#define STRINGS 5

#define DEDENT0 6

#define DEDENT_OUTPUT 7

#line 636 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 41 "lex"



	char comment[1000];
	comment[0] = 0;
	char hex[3];
	
	



#line 798 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 266 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 377 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 52 "lex"
{	
						if (dedents.count > 0){
							printf("DENT %d\n", dedents.DedentType);
							dedents.count--;
							return dedents.DedentType;
						}
						else	
							BEGIN(INITIAL);
				}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 62 "lex"
{;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 64 "lex"
{BEGIN(ONECOMMENT);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 65 "lex"
{;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 66 "lex"
{ BEGIN(INITIAL);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 69 "lex"
{BEGIN(DOUBLELONGSTRING); comment[0] = 0;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 70 "lex"
strcat(comment,"\n");
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 71 "lex"
strcat(comment,"\"");
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 72 "lex"
strcat(comment,"\\");
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 73 "lex"
strcat(comment,"\'");
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 74 "lex"
strcat(comment,"\'");
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 75 "lex"
strcat(comment,"\"");
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 76 "lex"

	YY_BREAK
case 14:
YY_RULE_SETUP
#line 77 "lex"
strcat(comment,"\a");
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 78 "lex"
strcat(comment,"\b");
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 79 "lex"
strcat(comment,"\f");
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 80 "lex"
strcat(comment,"\r");
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 81 "lex"
strcat(comment,"\t");
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 82 "lex"
strcat(comment,"\v");
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 83 "lex"
{
																	hex[0] = strtol(yytext + 2,0,16);
																	hex[1] = 0;
																	strcat(comment,hex);
																}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 88 "lex"
strcat(comment,yytext);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 89 "lex"
{
									char* string1 =(char *)malloc(strlen(comment)+1);
									string1[0] = 0;
									strcpy(string1, comment);
									yylval.string_value = string1;
									BEGIN(INITIAL);
									return STRING;
								}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 98 "lex"
{BEGIN(LONGSTRING); comment[0] = 0;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 99 "lex"
strcat(comment,"\n");
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 100 "lex"
strcat(comment,"\'");
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 101 "lex"
{
											char* string1 =(char *)malloc(strlen(comment)+1);
											string1[0] = 0;
											strcpy(string1, comment);
											yylval.string_value = string1;
											BEGIN(INITIAL);
											return STRING;
										}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 110 "lex"
{BEGIN(ONECOMMENT);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 111 "lex"
{;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 112 "lex"
{
				if( !(isLogicalString || parenthesesOpenCount || squarebracketsOpenCount || curlybracesOpenCount))
				{
					calcIndentation(indentStack, &indexTop, strlen(yytext), &dedents);
					BEGIN(DEDENT_OUTPUT);
				}
			}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 119 "lex"
{
				if( !(isLogicalString || parenthesesOpenCount || squarebracketsOpenCount || curlybracesOpenCount))
				{
					calcIndentation(indentStack, &indexTop, strlen(yytext)*4, &dedents);
					BEGIN(DEDENT_OUTPUT);
				}
			}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 126 "lex"
{
				if( !(isLogicalString || parenthesesOpenCount || squarebracketsOpenCount || curlybracesOpenCount))
				{
					printf("Error mixing tab and spacers on line %d\n", yylineno);
				}
			}
	YY_BREAK
case 32:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 132 "lex"
{
				if( !(isLogicalString || parenthesesOpenCount || squarebracketsOpenCount || curlybracesOpenCount))
				{
					calcIndentation(indentStack, &indexTop, 0, &dedents);
					BEGIN(DEDENT_OUTPUT);
				}
			}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 140 "lex"
{BEGIN(STRING_0);comment[0] = 0;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 141 "lex"
{printf("Error in string %d - String literal not closed",yylineno);BEGIN(INITIAL);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 142 "lex"
{
							char* string1 =(char *)malloc(strlen(comment)+1);
							string1[0] = 0;
							strcpy(string1, comment);
							yylval.string_value = string1;
							BEGIN(INITIAL);
							return STRING;
						}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 151 "lex"
{BEGIN(STRINGS);comment[0] = 0;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 152 "lex"
{
						char* string1 =(char *)malloc(strlen(comment)+1);
						string1[0] = 0;
						strcpy(string1, comment);
						yylval.string_value = string1;
						BEGIN(INITIAL);
						return STRING;
					}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 162 "lex"
{ return FALSE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 163 "lex"
{ return IF; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 164 "lex"
{ return IMPORT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 165 "lex"
{ return FROM; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 166 "lex"
{ return IN; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 167 "lex"
{ return IS; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 168 "lex"
{ return AS; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 169 "lex"
{ return LAMBDA; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 170 "lex"
{ return NOT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 171 "lex"
{ return OR; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 172 "lex"
{ return PASS; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 173 "lex"
{ return RAISE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 174 "lex"
{ return RETURN; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 175 "lex"
{ return TRY; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 176 "lex"
{ return WHILE; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 177 "lex"
{ return FOR; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 178 "lex"
{ return WITH; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 179 "lex"
{ return NONE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 180 "lex"
{ return TRUE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 181 "lex"
{ return AND; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 182 "lex"
{ return ASSERT; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 183 "lex"
{ return BREAK; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 184 "lex"
{ return CLASS; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 185 "lex"
{ return CONTINUE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 186 "lex"
{ return DEF; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 187 "lex"
{ return ELIF; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 188 "lex"
{ return ELSE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 189 "lex"
{ return EXCEPT; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 190 "lex"
{ return FINALLY; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 191 "lex"
{ return YIELD; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 192 "lex"
{ return '+'; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 193 "lex"
{ return '-'; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 194 "lex"
{ return '*'; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 195 "lex"
{ return POW; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 196 "lex"
{ return '/'; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 197 "lex"
{ return FLOOR_DIV; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 198 "lex"
{ return '%'; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 199 "lex"
{ return '@'; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 200 "lex"
{ return LEFT_SHIFT; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 201 "lex"
{ return RIGHT_SHIFT; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 202 "lex"
{ return '&'; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 203 "lex"
{ return '|'; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 204 "lex"
{ return '^'; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 205 "lex"
{ return '~'; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 206 "lex"
{ return '>'; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 207 "lex"
{ return '<'; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 208 "lex"
{ return LESSER_EQUAL; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 209 "lex"
{ return GREATER_EQUAL; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 210 "lex"
{ return EQUAL; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 211 "lex"
{ return NOT_EQUAL; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 212 "lex"
{ parenthesesOpenCount++; return '('; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 213 "lex"
{ parenthesesOpenCount--; return ')'; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 214 "lex"
{ squarebracketsOpenCount++; return '['; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 215 "lex"
{ squarebracketsOpenCount--; return ']'; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 216 "lex"
{ curlybracesOpenCount++; return '{'; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 217 "lex"
{ curlybracesOpenCount--; return '}'; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 218 "lex"
{ return ','; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 219 "lex"
{ return ':'; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 220 "lex"
{ return '.'; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 221 "lex"
{ return ';'; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 222 "lex"
{ return '='; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 223 "lex"
{ return ARROW; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 224 "lex"
{ return PLUS_ASSIGN; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 225 "lex"
{ return MINUS_ASSIGN; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 226 "lex"
{ return MULT_ASSIGN; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 227 "lex"
{ return DIV_ASSIGN; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 228 "lex"
{ return -1; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 229 "lex"
{ return MOD_ASSIGN; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 230 "lex"
{ return -1; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 231 "lex"
{ return -1; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 232 "lex"
{ return -1; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 233 "lex"
{ return -1; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 234 "lex"
{ return -1; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 235 "lex"
{ return -1; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 236 "lex"
{ return POW_ASSIGN; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 238 "lex"
{ yylval.float_value = atof(yytext); return FLOAT; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 239 "lex"
{ yylval.int_value = atoi(yytext); return INT; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 240 "lex"
{ yylval.string_value=(char *)malloc(strlen(yytext)+1); strcpy(yylval.string_value, yytext); return ID; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 242 "lex"
{printf("BACKSLASH\n"); isLogicalString = 1;}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 243 "lex"
{
				if( parenthesesOpenCount == 0 && squarebracketsOpenCount == 0 && curlybracesOpenCount == 0)
				{
					isLogicalString = 0;
					BEGIN(DEDENT0);
					return NEWLINE;
				}
			}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 252 "lex"
{;}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ONECOMMENT):
case YY_STATE_EOF(STRING_0):
case YY_STATE_EOF(DOUBLELONGSTRING):
case YY_STATE_EOF(LONGSTRING):
case YY_STATE_EOF(STRINGS):
case YY_STATE_EOF(DEDENT0):
case YY_STATE_EOF(DEDENT_OUTPUT):
#line 254 "lex"
{
			
			calcIndentation(indentStack, &indexTop, 0, &dedents);
			if (firstEOF == 0){
				
				if (dedents.count > 0) {
					printf("DENT FINISH %d\n", dedents.DedentType);
					dedents.count--;
					return dedents.DedentType;
				}
				else if (secondEOF == 1) {
					secondEOF = 0;
					yyterminate();
				}				
			}
			else {
				firstEOF = 0;
				return NEWLINE;
			}
		}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 274 "lex"
ECHO;
	YY_BREAK
#line 1591 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 266 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 266 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	*yy_state_ptr++ = yy_current_state;
	yy_is_jam = (yy_current_state == 265);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');
	if ( yy_current_buffer->yy_at_bol )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 274 "lex"


void calcIndentation(int* indentStack, int* indexTop, int len, struct DedentStruct* dedents)
{
	if( len > indentStack[*indexTop] )
	{
		(*indexTop)++;
		indentStack[*indexTop] = len;
		(*dedents).count = 1;
		(*dedents).DedentType = INDENT;
	}
	else if( len < indentStack[*indexTop])
	{
		int dedentCount = *indexTop;
		while(len < indentStack[dedentCount])
			dedentCount--;
			
		if (len != indentStack[dedentCount])
			printf("Error: inconsistent dedent %d\n", len);
		else
		{
			(*dedents).count = 0;
			(*dedents).DedentType = DEDENT;
			while(*indexTop > dedentCount)
			{
				(*dedents).count += 1;
				(*indexTop)--;
			}
		}
	}		
}

int main(int argc, char *argv[])
{
	yyin = fopen(argv[1], "r");
	yyparse();
	freopen("grammar_tree.txt","w",stdout);
	printTree();
	freopen("tree_to_python.txt","w",stdout);
	printForPython();
	_execlpe("cmd", "/c", "GrammarTreeImage.bat", "", 0,0,0);
	


	return 0;
}
